### ISSUE TITLE
Provide translations for all languages

### ISSUE THREAD

**Issue by flipwise** [flipwise/unibody-kickoff#1]
This Kickoff applet needs to be distinguished from the existing Kickoff provided by KDE.

I cannot provide the translations for other languages so for now I've simply added "(2)" to avoid confusion.

**Comment by flipwise** [comment]
Probably not too necessary.

**Comment by Zren** [comment]
In order to reuse kickoff's translations, you'll have to replace all `i18n(...)` calls with `i18nd("plasma_applet_org.kde.kickoff", ...)`.

https://github.com/KDE/plasma-workspace/blob/master/wallpapers/image/imagepackage/contents/ui/main.qml#L59

There's literally no examples, but you should be able to use [KLocalizedContext](https://api.kde.org/frameworks/ki18n/html/classKLocalizedContext.html) if you want to shorten the function call code. I remember playing around with that ages ago when trying to figure out how to bundle translations. 

```
    KLocalizedContext {
        id: asdf
        translationDomain: "plasma_applet_org.kde.kickoff"
    }

    Label {
        text: asdf.i18n(...)
    }
```

**Comment by flipwise** [comment]
Thanks, Zren!

I circumvented the problem for now by just having the package name match KDE's Kickoff. I have to think some more on if it's too dirty of a way out, and if so I'll have to start changing the QMLs.
